spring:
  #profiles:
  #default: test
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: 9719
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #to don't recreate table
server:
  servlet:
    context-path: /test #Defining for purpose of application.