spring:
  #profiles:
  #default: test
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 9719
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create #to don't recreate table
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


server:
  servlet:
    context-path: /test #Defining for purpose of application.
  port: 8987