spring:
  #profiles:
    #default: test
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: 9719
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #for recreating table
server:
  servlet:
    context-path: /test #Defining for purpose of application.